import 'package:aazioondoctorapp/chat/constants.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

TextStyle appBarStyle= GoogleFonts.montserrat(color: Colors.black,fontSize: width*.047,fontWeight: FontWeight.w400);
TextStyle searchBoxStyle= GoogleFonts.montserrat(color: Color.fromRGBO(207,217,232,1),fontSize: width*.04);
TextStyle citySearchBoxStyle= GoogleFonts.montserrat(color: Color.fromRGBO(207,217,232,1),fontSize: width*.043);
TextStyle searchResultText= GoogleFonts.montserrat(color: Colors.black,fontSize: width*.04);
TextStyle loginTextBoxText= GoogleFonts.montserrat(color: Colors.black,fontSize: width*.04);
TextStyle fullWidthButtonText= GoogleFonts.montserrat(color: Colors.white,fontSize: width*.04,fontWeight: FontWeight.w500);
TextStyle termConditionText= GoogleFonts.montserrat(color: Colors.black, fontSize: width * .03, wordSpacing: 2.2);
TextStyle normalBlackText= GoogleFonts.montserrat(color: Colors.black, fontSize: width * .04,fontWeight: FontWeight.w300);
TextStyle normalBlackBoldText= GoogleFonts.montserrat(color: Colors.black, fontSize: width * .04,fontWeight: FontWeight.w400);
TextStyle normalLightBlueText= GoogleFonts.montserrat(fontSize: width * .04,fontWeight: FontWeight.w300,color: Colors.blue[200]);
// TextStyle normalAppThemeColorBoldText= GoogleFonts.montserrat(fontSize: width * .04,fontWeight: FontWeight.w400,color:  appThemeColor,);
TextStyle homePageHeadingText= GoogleFonts.montserrat(fontSize: width * .045,  fontWeight: FontWeight.w400, color: Colors.black);
// TextStyle homePageHeadingThemeText= GoogleFonts.montserrat(fontSize: width * .0435,  fontWeight: FontWeight.w400, color: appThemeColor);
TextStyle homePageHeadingSmallText= GoogleFonts.montserrat(fontSize: width * .037,  fontWeight: FontWeight.w500, color: Colors.black);
TextStyle homePageHeadingSmallLightText= GoogleFonts.montserrat(fontSize: width * .037,  fontWeight: FontWeight.w300, color: Colors.black);
TextStyle homePageNormalBlackText= GoogleFonts.montserrat(color: Colors.black);
TextStyle defaultNormalBlackText= TextStyle(color: Colors.black);
TextStyle homePageNormalBoldBlackText= GoogleFonts.montserrat(color: Colors.black,fontWeight: FontWeight.w400);
// TextStyle homePageNormalThemeColorText= GoogleFonts.montserrat(color: appThemeColor);
TextStyle smallNormalBlackText= GoogleFonts.montserrat(color: Colors.black, fontSize: height * .014);
TextStyle homePageNormalSmallBlackText=GoogleFonts.montserrat(fontSize:width*.03, color: Colors.black,fontWeight: FontWeight.w400);
TextStyle homePageNormalSmallGreyText=GoogleFonts.montserrat(fontSize:width*.03, color: Colors.grey);
TextStyle cityNameText=GoogleFonts.montserrat(fontSize:width*.045, fontWeight: FontWeight.w500, color: Colors.black);
TextStyle drawerElementText=GoogleFonts.montserrat(fontSize:16, color: Colors.black);
TextStyle profilePageFieldName= GoogleFonts.montserrat(fontSize: width*.04,fontWeight: FontWeight.w400);
TextStyle profilePageFieldDetails= GoogleFonts.montserrat(fontSize: width*.04,fontWeight: FontWeight.w300);
TextStyle profilePageWhiteText= GoogleFonts.montserrat(color: Colors.white,fontSize: width*.04);
TextStyle prescriptionButtonText= GoogleFonts.montserrat(color: Colors.white,fontSize: width*.03,fontWeight: FontWeight.w300);
TextStyle whiteText= GoogleFonts.montserrat(color: Colors.white);
// TextStyle appointmentMainScreenHeadingText= GoogleFonts.montserrat(fontSize: width * .043,  fontWeight: FontWeight.w400, color: appThemeColor);
TextStyle clinicDetailsText= GoogleFonts.montserrat(fontSize: width * .035, fontWeight: FontWeight.w400,);
TextStyle normalGreyText = GoogleFonts.montserrat(color: Colors.grey, fontSize: width * .035,);
TextStyle cyanBoldText = GoogleFonts.montserrat(color: Color.fromRGBO(59, 216, 209, 1), fontSize: width * .038, fontWeight: FontWeight.w500);
TextStyle paymentPageDocNameText = GoogleFonts.montserrat(fontSize: width * .05, fontWeight: FontWeight.w400);
TextStyle paymentPageClinicNameText = GoogleFonts.montserrat(fontSize: width * .04, fontWeight: FontWeight.w200);
TextStyle pendingSmallText= GoogleFonts.montserrat(fontSize: width * .03,  fontWeight: FontWeight.w400, color: Colors.yellow);
TextStyle approvedSmallText= GoogleFonts.montserrat(fontSize: width * .03,  fontWeight: FontWeight.w400, color: Colors.green);
TextStyle greenNormalText= GoogleFonts.montserrat(fontSize: width * .035,  fontWeight: FontWeight.w400, color: Colors.green);
TextStyle rejectSmallText= GoogleFonts.montserrat(fontSize: width * .03,  fontWeight: FontWeight.w400, color: Colors.red);
TextStyle amountNormalText= GoogleFonts.montserrat(fontSize: width * .035,  fontWeight: FontWeight.w400, color: Colors.red);
TextStyle vaccinePageChildNameText= GoogleFonts.montserrat(fontSize: width * .04,  fontWeight: FontWeight.w400, );
TextStyle vaccinePageChildDetailsText= GoogleFonts.montserrat(fontSize: width * .03,  fontWeight: FontWeight.w400, );

